### ISSUE TITLE
put labelbox specific items in new file.

### ISSUE THREAD

**Issue by jsseng** [Gomer1800/Senior-Project#3]
Put the labelbox specific code in a new file.  Put the scale.ai specific items in a new file and put the generic code in a third file.

**Comment by Gomer1800** [comment]
Use python argParse instead of manual parsing done currently

**Comment by Gomer1800** [comment]
Implement ScaleAI stuff

**Comment by Gomer1800** [comment]
Use python JSON library to unpack json file

**Comment by Gomer1800** [comment]
Finished
